//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetTilausDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Esimiehet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Esimiehet()
        {
            this.Henkilots = new HashSet<Henkilot>();
        }
    
        public int EsimiesID { get; set; }
        public string Etunimi { get; set; }
        public string Sukunimi { get; set; }
        public string Titteli { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Henkilot> Henkilots { get; set; }
    }
}
