//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetTilausDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipper
    {
        public int ShipperID { get; set; }
        public string Nimi { get; set; }
        public string Osoite { get; set; }
        public string Postinumero { get; set; }
    
        public virtual Postitoimipaikat Postitoimipaikat { get; set; }
    }
}
